"""Generate frontend TypeScript types from backend Pydantic models and enums.

Run with: uv run python scripts/generate_types.py ../frontend/src/types/
Output: <types_dir>/MessageTypes.ts, <types_dir>/LocationTypes.ts, <types_dir>/HousingTypes.ts
"""

import sys
from enum import StrEnum
from pathlib import Path
from types import UnionType
from typing import Literal, Union, get_args, get_origin

from pydantic import BaseModel
from tenantfirstaid.location import Location, OregonCity, UsaState
from tenantfirstaid.schema import ResponseChunk

CHUNK_MODELS = list(get_args(ResponseChunk))
LOCATION_ENUMS: list[type[StrEnum]] = [OregonCity, UsaState]

HEADER = (
    "// This file is auto-generated by backend/scripts/generate_types.py.\n"
    "// Do not edit manually — re-run `make generate-types`."
)


def py_annotation_to_ts(annotation: type) -> str:
    """Convert a Python type annotation to a TypeScript type string."""
    origin = get_origin(annotation)
    args = get_args(annotation)

    if origin is Literal:
        return " | ".join(f'"{a}"' for a in args)
    if annotation is str:
        return "string"
    if isinstance(annotation, type) and issubclass(annotation, StrEnum):
        return f"T{annotation.__name__}"
    if origin in (UnionType, Union):
        ts_parts = [py_annotation_to_ts(a) for a in args if a is not type(None)]
        if type(None) in args:
            ts_parts.append("null")
        return " | ".join(ts_parts)

    raise TypeError(f"Unsupported annotation for TypeScript codegen: {annotation!r}")


def model_to_interface(model: type[BaseModel]) -> str:
    """Render a Pydantic BaseModel as a TypeScript interface."""
    lines = [f"interface I{model.__name__} {{"]
    for field_name, field_info in model.model_fields.items():
        lines.append(f"  {field_name}: {py_annotation_to_ts(field_info.annotation)};")
    lines.append("}")
    return "\n".join(lines)


def enum_to_ts_type(enum: type[StrEnum]) -> str:
    """Render a StrEnum as a TypeScript type alias."""
    members = " | ".join(f'"{e.value}"' for e in enum)
    return f"type T{enum.__name__} = {members};"


def make_file(blocks: list[str], exports: list[str], imports: str = "") -> str:
    """Assemble a TypeScript file from blocks, with optional imports."""
    parts = [HEADER]
    if imports:
        parts.append(imports)
    parts.extend(blocks)
    parts.append(f"export type {{ {', '.join(exports)} }};")
    return "\n\n".join(parts) + "\n"


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <types_dir>")
        sys.exit(1)

    types_dir = Path(sys.argv[1])

    ts_names = [f"I{m.__name__}" for m in CHUNK_MODELS]
    interfaces = [model_to_interface(m) for m in CHUNK_MODELS]
    union_alias = f"type TResponseChunk = {' | '.join(ts_names)};"

    files = {
        "MessageTypes.ts": make_file(
            interfaces + [union_alias],
            ["TResponseChunk", *ts_names],
        ),
        "LocationTypes.ts": make_file(
            [enum_to_ts_type(e) for e in LOCATION_ENUMS],
            [f"T{e.__name__}" for e in LOCATION_ENUMS],
        ),
        "HousingTypes.ts": make_file(
            [model_to_interface(Location)],
            [f"I{Location.__name__}"],
            imports='import type { TOregonCity, TUsaState } from "./LocationTypes";',
        ),
    }

    for filename, content in files.items():
        path = types_dir / filename
        path.write_text(content)
        print(f"Written to {path}")
