// This file is auto-generated by backend/scripts/generate_types.py.
// Do not edit manually — re-run `make generate-types`.

import type { TOregonCity, TUsaState } from "./LocationTypes";

interface ILocation {
  city: TOregonCity | null;
  state: TUsaState | null;
}

export type { ILocation };
