// This file is auto-generated by backend/scripts/generate_types.py.
// Do not edit manually — re-run `make generate-types`.

type TOregonCity = "portland" | "eugene";

type TUsaState = "or" | "other";

export type { TOregonCity, TUsaState };
