// This file is auto-generated by backend/scripts/generate_types.py.
// Do not edit manually — re-run `make generate-types`.

interface ITextChunk {
  type: "text";
  content: string;
}

interface IReasoningChunk {
  type: "reasoning";
  content: string;
}

interface ILetterChunk {
  type: "letter";
  content: string;
}

type TResponseChunk = ITextChunk | IReasoningChunk | ILetterChunk;

export type { TResponseChunk, ITextChunk, IReasoningChunk, ILetterChunk };
